version: '3'

services:

  backend:
    container_name: meu_bolsista_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: registry.gitlab.com/meu-bolsista/meu_bolsista:latest
    ports:
      - ${APP_PORT}:11000
    restart: always
