version: '3'

services:

  postgres:
    container_name: postgres-meu-bolsista
    image: postgres:15.4-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - ./postgresDB:/data/postgres
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    restart: unless-stopped