version: '3.9'

services:

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: registry.gitlab.alverad.com.br/meu-bolsista/meu_bolsista_api
    restart: always
    networks:
      - traefik-public
    environment:
      - TZ=America/Belem
    deploy:
      placement:
        constraints:
          - node.labels.service == api
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.meu_bolsista_api.rule=Host(`${DOMAIN_APPLICATION}`) && PathPrefix(`${API_PREFIX}`)"
        - "traefik.http.routers.meu_bolsista_api.entrypoints=http"
        - "traefik.http.routers.meu_bolsista_api.middlewares=meu_bolsista_api_strip@docker" # https-redirect@file"

        - "traefik.http.middlewares.meu_bolsista_api_strip.stripprefix.prefixes=${API_PREFIX}"
        - "traefik.http.middlewares.meu_bolsista_api_strip.stripprefix.forceslash=true"


        - "traefik.http.routers.meu_bolsista_api_https.rule=Host(`${DOMAIN_APPLICATION}`) && PathPrefix(`${API_PREFIX}`)"
        - "traefik.http.routers.meu_bolsista_api_https.entrypoints=https"
        - "traefik.http.routers.meu_bolsista_api_https.tls=true"
        - "traefik.http.routers.meu_bolsista_api_https.tls.certresolver={}"
        - "traefik.http.routers.meu_bolsista_api_https.middlewares=default-headers@file,meu_bolsista_api_strip@docker"
        - "traefik.http.services.meu_bolsista_api_https.loadbalancer.server.port=${APP_PORT}"

networks:
  traefik-public:
    external: true
