version: '3.9'

services:

  postgres:
    container_name: postgres-meu-bolsista
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    #volumes:
    #   - ./postgresDB:/data/postgres
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    restart: unless-stopped

  mongodb:
    container_name: mongo-meu-bolsista
    image: mongo:6
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # volumes:
    #   - mongo_report:/data/db
    #   - ./backup/:/backup/

  backend:
    container_name: meu-bolsista-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: meu-bolsista-api:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - mongodb
      - postgres

volumes:
  mongo_report:
    driver: local
