version: '3'

services:

  mongodb:
    container_name: mongo-meu-bolsista
    image: mongo:6
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_report:/data/db
      - ./backup/:/backup/

volumes:
  mongo_report:
    driver: local
