version: '3.9'

services:

  postgres:
    container_name: postgres-meu-bolsista
    build:
      context: .
      dockerfile: docker/Dockerfile.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    #volumes:
    #   - ./postgresDB:/data/postgres
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    restart: unless-stopped

  backend:
    container_name: meu-bolsista-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    image: meu-bolsista-api:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    depends_on:
      - postgres
