version: '3'

services:

  backend:
    container_name: meu_bolsista_api
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - PROFILE=prod
    env_file:
      - .env
    image: registry.gitlab.com/meu-bolsista/meu_bolsista_api:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
