version: '3.9'

x-service: &default-service
  build:
    context: .
    dockerfile: docker/Dockerfile
  environment:
    - TZ=America/Belem
  env_file:
      - .env


services:

  backend:
    <<: *default-service
    image: registry.gitlab.alverad.com.br/meu-bolsista/meu_bolsista_api
    restart: always


  backend_api_version:
    << : *default-service
    image: registry.gitlab.alverad.com.br/meu-bolsista/meu_bolsista_api:${DATE_VERSION}
