spring:
  profiles:
    default: homol
  application:
    name: Meu Bolsista API
  servlet:
    multipart:
      max-file-size: 5MB
  #configuração do jackson
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    defer-datasource-initialization: true

# Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
      oauth2:
        client:
          registration:
            google:
              clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
              clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 121189305185277
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: 234b0a903fb3607d5d9f
              clientSecret: 58ef599d592749cc3a14afbb3676af80423fbcae
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

# Swagger
springdoc:
  swagger-ui:
    use-root-path: true
  show-login-endpoint: true

  api-docs:
    path: /v3/api-docs

logging:
  file:
      name: /var/log/meuBolsistaApi.log
      path: /var/log
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    web: debug
    sql: info
    root: error

# keys
rsa:
  private-key:
    classpath:certs/private.pem
  public-key:
    classpath:certs/public.pem

# Server configuration
server:
  port: ${APP_PORT}
  forward-headers-strategy: framework
  compression:
    enabled: true
    min-response-size: 2048
    mime-types:
    - application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

token:
  domain: ${DOMAIN_COOKIE}
  expiresHours: ${TOKEN_EXPIRES_HOURS}

cors:
  allowedOrigins: ${ALLOWED_ORIGINS}

fotosDir: ${PATHFOTOS}
