logging:
  level:
    '[org.hibernate.stat]': debug

spring:
  #DEVTOOLS
  devtools:
    add-properties: true
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
      mongodb:
        host: ${MONGO_HOST}
        database: ${MONGO_DB}
        port: ${MONGO_PORT}
        username: ${MONGO_INITDB_ROOT_USERNAME}
        password: ${MONGO_INITDB_ROOT_PASSWORD}
        authentication-database: admin # habilitar autenticação
        auto-index-creation: true # Atualizar indices quando autlaizar o model.

  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      '[hibernate.format_sql]' : true
      '[hibernate.generate_statistics]' : true
      '[persistence.schema-generation.scripts.create-target]' : create.sql
