logging:
  level:
    "[org.hibernate.stat]": debug

spring:
  #DEVTOOLS
  devtools:
    add-properties: false

  # JPA properties
  jpa:
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": true

server:
  error:
    include-stacktrace: never
