spring:
  profiles:
    default: homol
  application:
    name: Meu Bolsista API
  servlet:
    multipart:
      max-file-size: 10MB
  #configuração do jackson
  jackson:
    default-property-inclusion: NON_NULL

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DB}
      port: ${MONGO_PORT}
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: admin # habilitar autenticação
      auto-index-creation: true # Atualizar indices quando autlaizar o model.

  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: ${KEYCLOACK_CLIENT_ID}
            clientSecret: ${KEYCLOACK_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: openid,profile,email,roles
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${KEYCLOACK_URL}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOACK_URL}
          jwk-set-uri: ${KEYCLOACK_URL}/protocol/openid-connect/certs

  # Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Swagger
springdoc:
  swagger-ui:
    filter: true
    use-root-path: true
  show-login-endpoint: true

  api-docs:
    path: /v3/api-docs

logging:
  file:
    name: /var/log/meuBolsistaApi.log
    path: /var/log
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    web: debug
    sql: info
    root: error

# keys
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

# Server configuration
server:
  port: ${APP_PORT}
  forward-headers-strategy: framework
  compression:
    enabled: true
    min-response-size: 2048
    mime-types:
      - application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

token:
  domain: ${DOMAIN_COOKIE}
  expiresHours: ${TOKEN_EXPIRES_HOURS}

cors:
  allowedOrigins: ${ALLOWED_ORIGINS}

services:
  anexos-store-api:
    base-url: ${ANEXOS_STORE_API}
    consultar-arquivo: ${ANEXOS_STORE_API}/arquivo/
    salvar-arquivo: ${ANEXOS_STORE_API}/arquivo
  registrationId: keycloak
